version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "11:00"
    timezone: US/Central
  open-pull-requests-limit: 99
  reviewers:
  - jackcmeyer
  assignees:
  - jackcmeyer
  ignore:
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.27
    - 14.14.31
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
